### ISSUE TITLE
Query only containing comment requires leading space

### ISSUE THREAD

**Issue by alastai** [opengql/editor#28] opened 2024-09-03 04:17 UTC
This is invalid:

<img width="265" alt="Screenshot 2024-09-03 at 12 14 55" src="https://github.com/user-attachments/assets/713b6374-4fc4-4e46-9e44-f7b2afd435cb">

But this is valid:

<img width="274" alt="Screenshot 2024-09-03 at 12 15 16" src="https://github.com/user-attachments/assets/5ce43dfd-afbb-492e-9a3d-7a544e76a377">

This is true if the comment is the only thing in the query, or is the prefix of the query.

**Comment by damianw27** [comment] 2024-09-03 08:00
The problem is with the order of the defined syntax objects in syntax highlight. I will provide a fix for this in the afternoon.

**Closed as completed** 2024-09-03 19:09 UTC
Labels: bug

**Comment by damianw27** [comment] 2024-09-03 19:12
Issue is solved:
![image](https://github.com/user-attachments/assets/9be393e9-ba34-43b0-9bed-45ecef5a916f)
